platform :ios, '9.0'
use_frameworks!

target 'TDAudio' do
    #log
    pod 'CleanroomLogger', '~> 5.1'

    #auto gen Resources
    pod 'R.swift'

    #back4app
    pod 'Parse'

    #Firebase
    pod 'Firebase/Core'
    pod 'Firebase/RemoteConfig'

    #json
    pod 'SwiftyJSON', '~> 3.1'

    #image
    pod 'SDWebImage', '~> 4.0'

    #checkbox
    pod 'UICheckbox.Swift', '~> 1.0'

    #fabric
    pod 'Fabric'
    pod 'Crashlytics'

    #admob ads
    pod 'Google-Mobile-Ads-SDK'

end
